### ISSUE TITLE
Support encoded secrets?

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/redactor#1]
The current implementation supports comma-delimited strings.  I would like to ensure that shell-unsafe bytes are allowed, too.   What's a reasonable encoding?  Example ideas:

``` bash
TRAVIS_SECRETS="b64:c2VjcmV0CmZvbwpiYXIKd2hhdGViZWJlcgo="
```

``` bash
TRAVIS_SECRETS="json:\"secretæ≤≥πwow\",\"huh™ª\",\"øåøåø\"]"
```

**Comment by joecorcoran** [comment]
Great point. Base 64 sounds decent? Maybe using [this lib](https://github.com/alicemaz/rust-base64).

FWIW, I'm not 100% sold on the env var – it could just as easily be an argument to the command if that's better. Whatever is easiest.

**Comment by joecorcoran** [comment]
Hmm, I guess there needs to be a delimiter somehow and if the whole array of secrets is encoded, there's no way to determine the semantics of `,`. This makes me think [command options](https://doc.rust-lang.org/getopts/getopts/struct.Options.html#method.optmulti) might be better.

```
$ ./redactor "./build.sh" -s c2VjcmV0 -s ZWJlcgo=
```

**Comment by meatballhat** [comment]
I'm a fan of supporting env vars whenever possible 😁   I think the command options way is cool, too.  What about :boom: ?:

``` bash
TRAVIS_SECRETS="base64:ZuKEouKEouKEouKEogo=,ascii:foo,ascii:bar,base64:d8WTdAo=" ./redactor ./build.sh

# a.k.a.:

./redactor ./build.sh -s base64:ZuKEouKEouKEouKEogo= -s ascii:foo -s ascii:bar -s base64:d8WTdAo=
```

**Comment by joecorcoran** [comment]
Cool, okay – I'll add the encoding now. 👍

**Comment by joecorcoran** [comment]
Alright, as of [v0.1.0-pre6](https://github.com/travis-ci/redactor/releases/tag/v0.1.0-pre6) we're doing encoded secrets. 🎉
